### PR TITLE
Adding a LICENSE file

### PR DESCRIPTION
**Pull request by craigspaeth**
I'd like to suggest adding an MIT license file to this repo.

### CODE REVIEW

**Comment by dblock** [comment]
This also needs a line in package.json.

**Comment by OliverJAsh** [comment]
I no longer have admin permissions :open_mouth:. @theefer Can you merge this please?

**Comment by rrees** [comment]
Guardian software is generally licensed under Apache2. Would that work for you @craigspaeth

**Comment by craigspaeth** [comment]
@rrees: Sure would thanks! Feel free to close this PR in favor of an Apache2 license.

**Comment by dblock** [comment]
I opened https://github.com/guardian/scribe-plugin-keyboard-shortcuts/pull/5. Would really appreciate if someone could hit merge, we have to make some non-engineers happy. 

FWIW would be nice if someone at Guardian went over all your projects, lots are missing a license.

**Comment by rrees** [comment]
Done even though we're at [our hack day](http://www.theguardian.com/info/developer-blog/live/2015/feb/26/guardian-hack-day-february-2015-liveblog)

In general terms if our projects do not have a license then they are _not_ open source, as your non-engineers have pointed out. We have a lot of projects that are open but not open source. Please raise an issue about the status of a project without a license and we'll consider it from there.

**Comment by dblock** [comment]
Thanks @rrees and good luck with the hack day!

IANAL, but in practice, a lot of engineers aren't careful about selecting third-party components and don't regularly check licenses, so maybe stick a CC non-commercial or some other educational license there by default - it protects both you and them.

That aside, I encourage you to give away your best stuff and maybe join us in [becoming open-source by default](http://code.dblock.org/2015/02/09/becoming-open-source-by-default.html) one day!

**Comment by rrees** [comment]
@dblock Here's [my equivalent](http://www.theguardian.com/info/developer-blog/2014/nov/28/developing-in-the-open) but there's a follow up to be had about why open source can be a difficult default position.

**Pull request closed without merging**
